import { AuthProvider } from "./Providers";
import { authOptions } from "../app/api/auth/[...nextauth]/route";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  
      const session = await getServerSession(authOptions);

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar session={session}/>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
